// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxcxkqbbpdtvvjlmbrii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4Y3hrcWJicGR0dnZqbG1icmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzAwODIsImV4cCI6MjA2ODE0NjA4Mn0.8HYvlviVN7SQ13pNLE1nAPjxKY011TPF7bUeXSSgkSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});